export const HOME_ROUTE = '/home'
export const BLOG_ROUTE = '/blog'
export const ELEMENTS_ROUTE = '/elements'
export const PORTFOLIO_ROUTE = '/portfolio'
export const LOGIN_ROUTE = '/login'
export const SIGNUP_ROUTE = '/signup'
