"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Login = exports.Portfolio = exports.Elements = exports.Blog = exports.Home = void 0;
var Home_1 = require("./Home");
exports.Home = Home_1.default;
var Blog_1 = require("./Blog");
exports.Blog = Blog_1.default;
var Elements_1 = require("./Elements");
exports.Elements = Elements_1.default;
var Portfolio_1 = require("./Portfolio");
exports.Portfolio = Portfolio_1.default;
var Login_1 = require("./Login");
exports.Login = Login_1.default;
